spring:
  application:
    name: mini_e_comerce

  datasource:
    url: jdbc:mysql://localhost:3306/miniEcomerce?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
